version: '3'
services:
  # webserver:
  #   image: node:20-buster
  #   container_name: 'lib-tmpl-node'
  #   command: 'npm /app/run test'
  #   ports:
  #     - "5000:5000"
  #   links:
  #     - database
  #     # - redis
  #   volumes:
  #     - ./:/app
  #     - ./.env:/.env
  #     - ./.env.testing:/.env.testing
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'mysqlroot'
  database:
    image: mysql:8.0
    container_name: 'lib-tmpl-mysql'
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysqld.conf:/etc/mysql/conf.d/mysqld.conf
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlroot'
      MYSQL_DATABASE: 'test_orm'
  # redis:
  #   container_name: 'lib-tmpl-redis'
  #   image: redis/redis-stack-server:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data
